import Head from "next/head";
import Image from "next/image";

import styled from "styled-components";
import { Articles } from "../components/sections/Articles";
import { Landing } from "../components/sections/Landing";
import { Projects } from "../components/sections/Projects";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StMain>
        <Landing />
        <Projects />
        <Articles />
      </StMain>
    </>
  );
}

const StMain = styled.main`
  background-color: black;
  height: 100vh;
  padding: 16px;
  overflow-y: scroll;
`;
